# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='finename',
            new_name='filename',
        ),
    ]
