# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='filename',
            new_name='postname',
        ),
    ]
