# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170410_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=users.models.Users, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
