# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 01:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170410_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='owner',
            field=models.ForeignKey(on_delete=users.models.Users, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
