# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170411_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
