# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_post_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='encMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('encrypted_message', models.TextField(max_length=7500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=users.models.Users, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
