# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_encmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encmessages',
            name='encrypted_message',
            field=models.TextField(max_length=7500, null=True),
        ),
    ]
