# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20170424_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encmessages',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postname',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
