# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20170424_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encmessages',
            name='encrypted_message',
            field=models.TextField(default=1, max_length=7500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encmessages',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
