# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20170424_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=users.models.Post.upload_to),
        ),
    ]
